working-directory = home
window-inherit-working-directory = false

shell-integration = none

window-padding-x = 5
window-padding-y = 5

copy-on-select = clipboard

keybind = ctrl+shift+delete=reset

keybind = alt+h=goto_split:left
keybind = alt+l=goto_split:right
keybind = alt+k=goto_split:top
keybind = alt+j=goto_split:bottom

keybind = ctrl+tab=unbind
keybind = ctrl+shift+tab=unbind
