macos-option-as-alt = true
macos-titlebar-style = tabs
auto-update = download
auto-update-channel = stable

# move to global on >=1.3.0
window-inherit-working-directory = false
tab-inherit-working-directory = false
split-inherit-working-directory = true

# move default find out of the way
keybind = super+shift+f=start_search
keybind = super+f=unbind

# handle these explicitly in fish
keybind = alt+arrow_left=unbind
keybind = alt+arrow_right=unbind
