#!/bin/sh

export LC_CTYPE="en_US.UTF-8"
export _JAVA_AWT_WM_NONREPARENTING=1

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
  eval $(dbus-launch --exit-with-session --sh-syntax)
fi
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
  dbus-update-activation-environment DISPLAY XAUTHORITY
fi

# NEEDED FOR NVIDIA DRIVERS
if [ -x "$(command -v nvidia-smi)" ]; then
  xrandr --setprovideroutputsource modesetting NVIDIA-0
fi

# NEEDED FOR CHROMEBOOK
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

xrandr --auto

xsetroot -cursor_name left_ptr

xset r rate 300 50

systemctl --user start graphical-session.target
systemctl --user start tray.target

exec systemd-cat --identifier=xmonad xmonad
