#!/usr/bin/env sh

export LC_CTYPE="en_US.UTF-8"
export _JAVA_AWT_WM_NONREPARENTING=1

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
xprofile=$HOME/.xprofile
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f "$xprofile" ]; then
  # shellcheck disable=SC1090
  . "$xprofile"
fi

# merge in defaults and keymaps
if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
  eval "$(dbus-launch --exit-with-session --sh-syntax)"
fi

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
  dbus-update-activation-environment DISPLAY XAUTHORITY
fi

# NEEDED FOR NVIDIA DRIVERS
if [ -x "$(command -v nvidia-smi)" ]; then
  xrandr --setprovideroutputsource modesetting NVIDIA-0
fi

[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap

# shellcheck disable=SC1091
. "$HOME"/.nix-profile/bin/configure-gtk

sudo systemctl start autorandr

touchpadid="$(xinput list | rg "SYNA.*Touchpad" | sort | tail -n 1 | awk '{print $6}' | cut -f 2 -d=)"
xinput disable "$touchpadid"

xsetroot -cursor_name left_ptr

xset r rate 300 50

systemctl --user start xserver-session.target
systemctl --user start tray.target

systemctl --user restart dunst
systemctl --user restart gammastep

systemd-cat --identifier=xmonad xmonad

systemctl --user stop xserver-session.target
systemctl --user stop tray.target
