tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "bash"
brew "bat"
brew "colordiff"
brew "coreutils"
brew "dark-mode"
brew "direnv"
brew "gh"
brew "git"
brew "git-crypt"
brew "xz"
brew "glib"
brew "gnu-sed"
brew "gnu-tar"
brew "pkg-config"
brew "gnupg"
brew "gotop"
brew "grep"
brew "htop"
brew "httpie"
brew "iftop"
brew "iperf3"
brew "jq"
brew "mas"
brew "mask"
brew "mtr"
brew "netcat"
brew "nmap"
brew "p7zip"
brew "pinentry-mac"
brew "pstree"
brew "pwgen"
brew "ranger"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "ruby"
brew "shellcheck"
brew "sipcalc"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"
cask "finicky"
cask "firefox"
cask "font-jetbrains-mono-nerd-font"
cask "gimp"
cask "istat-menus"
cask "joplin"
cask "kap"
cask "karabiner-elements"
cask "kitty"
cask "plexamp"
cask "pocket-casts"
cask "rectangle"
cask "sonos"
cask "spotify"
cask "visual-studio-code"
cask "xquartz"
cask "yubico-yubikey-manager"
mas "1Password 7", id: 1333542190
mas "GarageBand", id: 682658836
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Webcam Settings", id: 533696630
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
