#!/usr/bin/env bash

if [[ "$TERM_PROGRAM" == "vscode" ]]
then
  if [[ $TERM_PROGRAM_VERSION == *-insider ]]; then
    exec code-insiders --wait $@
  else
    exec code --wait $@
  fi
else
  exec vim $@
fi
