#!/usr/bin/env bash

if [[ "$TERM_PROGRAM" == "vscode" ]]
then
  if [[ $TERM_PROGRAM_VERSION == *-insider ]]; then
    exec code-insiders --wait $@
  else
    exec code --wait $@
  fi
elif command -v emacsclient &>/dev/null; then
  if [[ -e ~/.terminfo/78/xterm-emacs ]]; then
    export TERM=xterm-emacs
  else
    export TERM=xterm-256color
  fi
  exec emacsclient -t $@
else
  exec vim $@
fi
