#!/usr/bin/env sh

set -e

CONFIG="install.conf.yaml"
OSCONFIG="install.$(uname).yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="${HOME}/.dotfiles"

cd "${BASEDIR}"

# delete some stock files
[ -h $HOME/.bashrc ] || rm -fv $HOME/.bashrc
[ -h $HOME/.bash_profile ] || rm -fv $HOME/.bash_profile

if [ ! -e ~/.asdf ]; then
  make bootstrap-asdf
  . $HOME/.asdf/asdf.sh
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" -p ~/.dotfiles/dotbot-git/git.py "${@}"

if [ -e "$OSCONFIG" ]; then
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${OSCONFIG}" -p ~/.dotfiles/dotbot-git/git.py "${@}"
fi

HOSTCONFIG="install.$(hostname -s).yaml"
if [ -e $HOSTCONFIG ]; then
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${HOSTCONFIG}" -p ~/.dotfiles/dotbot-git/git.py "${@}"
fi
