#!/usr/bin/env sh

if ! command -v nix >/dev/null 2>&1; then
  curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm --diagnostic-endpoint=""

  # shellcheck disable=SC1091
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
rm -rf ~/.config/fish

case "$(uname)" in
Darwin)
  nix --extra-experimental-features "nix-command flakes" develop .# -c just nix-darwin-bootstrap
  ;;
Linux)
  nix --extra-experimental-features "nix-command flakes" run .#hm -- switch
  ;;
*)
  echo "nope, unsupported platform"
  ;;
esac
