#!/bin/bash

# Set highlight color to orange
defaults write NSGlobalDomain AppleHighlightColor -string "1.000000 0.874510 0.701961"

# turn off bluetooth when sleeping
defaults -currentHost write com.apple.Bluetooth RemoteWakeEnabled -bool false

# Turn on app auto-update
defaults write com.apple.commerce AutoUpdate -bool true
