format = "[╭─](fg:244) $all"

[aws]
disabled = true

[character]
format = "[╰─](fg:244)$symbol "
success_symbol = "[❯](bold yellow)"
error_symbol = "[❯](bold red)"

[gcloud]
format = '[$symbol$project]($style) '

[git_branch]
format = "[$symbol$branch]($style) "

[hostname]
style = 'bold yellow'
format = '[$hostname]($style) '

[nodejs]
disabled = true

[ruby]
disabled = true

[username]
style_user = 'fg:244'
format = '[$user@]($style)'
