# format = "[─](fg:244) $all"

[aws]
disabled = true

[character]
#format = "[╰─](fg:244)$symbol "
format = "[─](fg:244)$symbol "
success_symbol = "[❯](bold yellow)"
error_symbol = "[❯](bold red)"

[container]
disabled = true

[gcloud]
disabled = true
format = '[$symbol$project]($style) '

[git_branch]
format = "[$symbol$branch]($style) "

[hostname]
style = 'bold yellow'
format = '[$hostname]($style) '

[localip]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[username]
style_user = 'fg:244'
format = '[$user@]($style)'
