version: "3"

includes:
  firefox: ./taskfiles/firefox.yml
  test: ./taskfiles/test.yml
  windows: ./taskfiles/windows.yml

tasks:
  aqua-install:
    cmds:
      - install-aqua.sh -i ~/bin/aqua

  test:
    cmds:
      - task: test:build
