version: "3"

includes:
  os: ./tasks/Taskfile_{{OS}}.yml

tasks:
  asdf-install:
    cmds:
      - "[ -e ~/.asdf ] || git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0"
      - $HOME/.asdf/bin/asdf plugin list | grep -q direnv || $HOME/.asdf/bin/asdf plugin add direnv
      - $HOME/.asdf/bin/asdf global direnv system

  asdf-update:
    cmds:
      - $HOME/.asdf/bin/asdf update
      - "if [ -e ${HOME}/.asdf/plugins ]; then ${HOME}/.asdf/bin/asdf plugin-update --all; fi"

  aqua-install:
    cmds:
      - install-aqua.sh -i ~/bin/aqua

  bootstrap:
    cmds:
      - task: cleanup
      - task: dotbot
      - task: vim-plug
      - task: fish-bootstrap

  brew-bundle:
    cmds:
      - brew bundle

  brew-bundle-dump:
    cmds:
      - brew bundle dump --force

  brew-install:
    cmds:
      - ~/.dotfiles/bin/install-brew.sh

  cleanup:
    cmds:
      - task: cleanup-direnv
      - task: cleanup-asdf-direnv

  cleanup-direnv:
    cmds:
      - rm -rf ~/.config/direnv
    status:
      - test -L ~/.config/direnv

  cleanup-asdf-direnv:
    cmds:
      - ~/.asdf/bin/asdf plugin remove direnv || true
      - ~/.asdf/bin/asdf plugin add direnv
      - ~/.asdf/bin/asdf global direnv system
    status:
      - test ! -d ~/.asdf || ~/.asdf/bin/asdf list direnv 2>&1 | grep "No versions installed"

  dev:
    cmds:
      - task: asdf-install
      - task: asdf-update
      - ~/.dotfiles/bin/install-dev.sh

  dotbot:
    cmds:
      - ./bin/dotbot

  firefox-patch:
    dir: "{{ .FIREFOX_PROFILE }}"
    cmds:
      - test -n "{{ .FIREFOX_PROFILE }}"
      - test -d "{{ .FIREFOX_PROFILE }}"
      - "! pgrep -i firefox"
      - cp ~/.dotfiles/firefox/arkenfox/{prefsCleaner.sh,updater.sh,user.js} .
      - ln -sf ~/.dotfiles/firefox/user-overrides.js .
      - ./updater.sh -s
      - bash ./prefsCleaner.sh -s

  fish-bootstrap:
    cmds:
      - fish ~/.dotfiles/bin/theme.fish

  fisher-update:
    cmds:
      - fish -c "source ~/.dotfiles/fish/functions/fisher.fish; fisher update"

  mimeapps-fix:
    cmds:
      - mv ~/.config/mimeapps.list .
      - task: dotbot

  terminfo-custom:
    cmds:
      - tic -x -o $HOME/.terminfo xterm-screen-256color.terminfo

  terminfo-emacs:
    cmds:
      - tic -x -o $HOME/.terminfo xterm-emacs.terminfo

  test:
    cmds:
      - task: test-build
      - podman run --rm -it -v $PWD:/root/.dotfiles dotfiles-test sh -c "cd /root/.dotfiles; ./install"

  test-build:
    cmds:
      - podman build --tag dotfiles-test .
    status:
      - podman images | rg dotfiles-test

  test-shell:
    cmds:
      - task: test-build
      - podman run --rm -it localhost/dotfiles-test fish

  vim-plug:
    cmds:
      - "vim +PlugClean! +PlugUpdate +qall"

  vscode:
    cmds:
      - vscode-extensions.fish

  windows-terminal-backup:
    cmds:
      - cp /mnt/c/Users/adam/AppData/Local/Packages/Microsoft.WindowsTerminalPreview_*/LocalState/settings.json ./windowsterminal-settings.json
      - chmod 644 windowsterminal-settings.json

  zsh-prof:
    cmds:
      - time zsh -i -c exit

  zsh-prof-setup:
    cmds:
      - chmod +w ~/.zshrc
      - ex -sc '1i|zmodload zsh/zprof' -cx ~/.zshrc
      - echo "zprof" >> ~/.zshrc
