version: "3"

includes:
  os: ./tasks/Taskfile_{{OS}}.yml

tasks:
  bootstrap:
    cmds:
      - task: dotbot
      - task: vim-plug

  dotbot:
    cmds:
      - ./install

  terminfo-custom:
    cmds:
      - tic -x -o $HOME/.terminfo xterm-screen-256color.terminfo

  terminfo-emacs:
    cmds:
      - tic -x -o $HOME/.terminfo xterm-emacs.terminfo

  vim-plug:
    cmds:
      - "vim +PlugClean! +PlugUpdate +qall"
