version: "3"

includes:
  brew: ./taskfiles/brew.yml
  dev: ./taskfiles/dev.yml
  firefox: ./taskfiles/firefox.yml
  fish: fish/Taskfile.yml
  migrate: ./taskfiles/migrate.yml
  os: ./taskfiles/Taskfile_{{OS}}.yml
  test: ./taskfiles/test.yml
  vim: ./taskfiles/vim.yml
  windows: ./taskfiles/windows.yml

tasks:
  aqua-install:
    cmds:
      - install-aqua.sh -i ~/bin/aqua

  aqua-run:
    dir: "./aqua"
    cmds:
      - aqua install

  bootstrap:
    cmds:
      - task: migrate:all
      - task: aqua-run
      - task: dotbot
      - task: fish:bootstrap
      - task: lefthook:install

  bootstrap:slim:
    cmds:
      - task: dotbot

  dev:
    cmds:
      - ~/.dotfiles/bin/install-dev.sh
      - task: dev:all

  dotbot:
    cmds:
      - ./bin/dotbot

  git:setup:
    cmds:
      - git config -f ~/.gitconfig.local user.email {{.EMAIL}}

  lefthook:install:
    cmds:
      - lefthook install

  mimeapps:fix:
    cmds:
      - mv ~/.config/mimeapps.list .
      - task: dotbot

  ssh:keygen:
    cmds:
      - ssh-keygen -t ed25519

  test:
    cmds:
      - task: test:build

  vscode:
    cmds:
      - vscode-extensions.sh

  zsh-prof:
    cmds:
      - time zsh -i -c exit

  zsh-prof-setup:
    cmds:
      - chmod +w ~/.zshrc
      - ex -sc '1i|zmodload zsh/zprof' -cx ~/.zshrc
      - echo "zprof" >> ~/.zshrc
