version: "3"

includes:
  brew: ./taskfiles/brew.yml
  dev: ./taskfiles/dev.yml
  fish: fish/Taskfile.yml
  migrate: ./taskfiles/migrate.yml
  os: ./taskfiles/Taskfile_{{OS}}.yml
  test: ./taskfiles/test.yml

tasks:
  aqua-install:
    cmds:
      - install-aqua.sh -i ~/bin/aqua

  aqua-run:
    dir: "./aqua"
    cmds:
      - aqua install

  bootstrap:
    cmds:
      - task: migrate:all
      - task: aqua-run
      - task: dotbot
      - task: vim:plug
      - task: fish:bootstrap
      - task: lefthook:install

  bootstrap:slim:
    cmds:
      - task: dotbot

  dev:
    cmds:
      - ~/.dotfiles/bin/install-dev.sh
      - task: dev:all

  dotbot:
    cmds:
      - ./bin/dotbot

  firefox:patch:
    dir: "{{ .FIREFOX_PROFILE }}"
    cmds:
      - test -n "{{ .FIREFOX_PROFILE }}"
      - test -d "{{ .FIREFOX_PROFILE }}"
      - "! pgrep -i firefox"
      - cp ~/.dotfiles/firefox/arkenfox/{prefsCleaner.sh,updater.sh,user.js} .
      - ln -sf ~/.dotfiles/firefox/user-overrides.js .
      - ./updater.sh -s
      - bash ./prefsCleaner.sh -s

  git:setup:
    cmds:
      - git config -f ~/.gitconfig.local user.email {{.EMAIL}}

  lefthook:install:
    cmds:
      - lefthook install

  mimeapps:fix:
    cmds:
      - mv ~/.config/mimeapps.list .
      - task: dotbot

  test:
    cmds:
      - task: test:build

  vim:plug:
    cmds:
      - "vim +PlugClean! +PlugUpdate +qall"

  vscode:
    cmds:
      - vscode-extensions.fish

  windows-terminal-backup:
    cmds:
      - cp /mnt/c/Users/adam/AppData/Local/Packages/Microsoft.WindowsTerminalPreview_*/LocalState/settings.json ./windowsterminal-settings.json
      - chmod 644 windowsterminal-settings.json

  zsh-prof:
    cmds:
      - time zsh -i -c exit

  zsh-prof-setup:
    cmds:
      - chmod +w ~/.zshrc
      - ex -sc '1i|zmodload zsh/zprof' -cx ~/.zshrc
      - echo "zprof" >> ~/.zshrc
