version: "3"

includes:
  os: ./tasks/Taskfile_{{OS}}.yml

tasks:
  bootstrap:
    cmds:
      - task: dotbot
      - task: vim-plug

  brew-bundle:
    cmds:
      - brew bundle

  brew-bundle-dump:
    cmds:
      - brew bundle dump --force

  brew-install:
    cmds:
      - ~/.dotfiles/bin/install-brew.sh

  dotbot:
    cmds:
      - ./install

  mimeapps-fix:
    cmds:
      - mv ~/.config/mimeapps.list .
      - task: dotbot

  terminfo-custom:
    cmds:
      - tic -x -o $HOME/.terminfo xterm-screen-256color.terminfo

  terminfo-emacs:
    cmds:
      - tic -x -o $HOME/.terminfo xterm-emacs.terminfo

  vim-plug:
    cmds:
      - "vim +PlugClean! +PlugUpdate +qall"

  vscode:
    cmds:
      - vscode-extensions.fish
