[bar.default]
position = "top"
center = ["media"]
concave_edge_corners = false
end = [
  "tray",
  "notifications",
  "clipboard",
  "network",
  "bluetooth",
  "volume",
  "brightness",
  "battery",
  "control-center",
  "session",
  "clock",
]
font_family = "IBM Plex Sans"
margin_ends = 0
radius = 0
shadow = false

[desktop_widgets]
enabled = false

[idle]
publish_logind_idle_hint = true

[location]
auto_locate = true

[nightlight]
enabled = true
temperature_night = 3000

[notification]
position = "top_center"

[shell.animation]
enabled = false

[shell]
font_family = "IBM Plex Sans"
external_ip_enabled = false
launch_apps_as_systemd_services = true
password_style = "random"
polkit_agent = true

[system.monitor]
enabled = false

[theme]
builtin = "Ayu"
community_palette = "One"
mode = "dark"
pure_black_dark = true
wallpaper_scheme = "m3-tonal-spot"

[wallpaper.default]
path = "color:#000000"

[widget.clock]
format = "{:%d-%b %H:%M}"

[widget.control-center]
enabled = false

[widget.launcher]
enabled = false

[widget.media]
hide_when_no_media = true
max_length = 320

[widget.tray]
anchor = true

[widget.wallpaper]
enabled = false

[widget.workspaces]
style = "minimal"
