on: [push]

env:
  ATTIC_KEY: ${{ secrets.ATTIC_KEY }}

jobs:
  flake-build:
    runs-on: stop/${{ matrix.system }}

    strategy:
      matrix:
        system:
          - aarch64-darwin

    steps:
      - uses: actions/checkout@v4

      - run: flake-build --attic-use=true --nom=false --system ${{ matrix.system }}
