on: [push]

jobs:
  flake-build:
    runs-on: local/${{ matrix.system }}

    strategy:
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
          - aarch64-darwin

    steps:
      - uses: actions/checkout@v4

      - run: |
          export HOME=$PWD
          nix develop .# --command seed-ci --attic-use=true --nom=false --system ${{ matrix.system }}
        env:
          ATTIC_KEY: ${{ secrets.ATTIC_KEY }}
          ATTIC_URL: ${{ vars.ATTIC_ENDPOINT }}
          ATTIC_CACHE: ${{ vars.ATTIC_CACHE }}
