on:
  push:

env:
  ATTIC_URL: ${{ vars.ATTIC_URL }}
  ATTIC_CACHE: ${{ vars.ATTIC_CACHE }}
  ATTIC_KEY: ${{ secrets.ATTIC_KEY }}
  NTFY_HOST: ${{ vars.NTFY_HOST }}
  NTFY_USER: ${{ secrets.NTFY_USER }}
  NIKS3_SERVER_URL: ${{ vars.NIKS3_SERVER_URL }}

jobs:
  build-and-seed-aarch64:
    runs-on: local/aarch64-linux

    steps:
      - uses: actions/checkout@v4

      - name: next
        run: |
          printf '%s' '${{ secrets.NIKS3_AUTH_TOKEN }}' > ../niks3-token
          export NIKS3_AUTH_TOKEN_FILE="$PWD/../niks3-token"
          nix develop .#ci --command attic login junco $ATTIC_URL --set-default $ATTIC_KEY
          nix develop .#ci --command sower build --cache niks3:// --cache attic://junco:$ATTIC_CACHE --eval-jobs 1 --seed .#sowerJobs.aarch64-linux.home/aarch64-linux
          nix develop .#ci --command sower build --cache niks3:// --cache attic://junco:$ATTIC_CACHE --eval-jobs 1 --seed .#sowerJobs.aarch64-linux.home/nixos2
        env:
          SOWER_ENDPOINT: ${{ vars.SOWER_NEXT_ENDPOINT }}
          SOWER_ACCESS_TOKEN: ${{ secrets.SOWER_ACCESS_TOKEN }}

      - name: Notify on failure
        if: failure()
        run: |
          nix develop .#ci --command \
            ntfy send \
            --click="${{ forgejo.server_url}}/${{ forgejo.repository }}/actions/runs/${{ forgejo.run_number }}/jobs/${{ forgejo.job }}/attempt/${{ forgejo.run_attempt }}" \
            ${{ vars.NTFY_HOST }}/alerts \
            "Build failure in ${FORGEJO_REPOSITORY}"

  build-and-seed-x86_64:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - name: next
        run: |
          printf '%s' '${{ secrets.NIKS3_AUTH_TOKEN }}' > ../niks3-token
          export NIKS3_AUTH_TOKEN_FILE="$PWD/../niks3-token"
          nix develop .#ci --command attic login junco $ATTIC_URL --set-default $ATTIC_KEY
          nix develop .#ci --command sower build --cache niks3:// --cache attic://junco:$ATTIC_CACHE --eval-jobs 12 .#sowerJobs.x86_64-linux --seed
        env:
          SOWER_ENDPOINT: ${{ vars.SOWER_NEXT_ENDPOINT }}
          SOWER_ACCESS_TOKEN: ${{ secrets.SOWER_ACCESS_TOKEN }}

      - name: Notify on failure
        if: failure()
        run: |
          nix develop .#ci --command \
            ntfy send \
            --click="${{ forgejo.server_url}}/${{ forgejo.repository }}/actions/runs/${{ forgejo.run_number }}/jobs/${{ forgejo.job }}/attempt/${{ forgejo.run_attempt }}" \
            ${{ vars.NTFY_HOST }}/alerts \
            "Build failure in ${FORGEJO_REPOSITORY}"

  sower-dev:
    runs-on: local/x86_64-linux

    steps:
      - uses: actions/checkout@v4

      - name: next
        run: |
          printf '%s' '${{ secrets.NIKS3_AUTH_TOKEN }}' > ../niks3-token
          export NIKS3_AUTH_TOKEN_FILE="$PWD/../niks3-token"
          nix develop .#ci --command attic login junco $ATTIC_URL --set-default $ATTIC_KEY

          nix develop .#ci --command sower build \
            --cache niks3:// \
            --cache attic://junco:$ATTIC_CACHE \
            --memory-limit 5600 \
            --seed \
            --tag dev=true \
            .#sowerJobs.x86_64-linux.home/agents
        env:
          SOWER_ENDPOINT: ${{ vars.SOWER_DEV_ENDPOINT }}
          SOWER_ACCESS_TOKEN: ${{ secrets.SOWER_DEV_ACCESS_TOKEN }}
