input-field {
  fade_on_empty = false
  rounding = 0
  dots_center = false
  dots_size = 0.2
  outer_color = rgba(FF5189EE) rgba(E3C78AEE) 45deg
  inner_color = rgb(9E9E9E)
  placeholder_text =
}

background {
  color = rgb(080808)
}

