brewfile := "Brewfile." + `hostname -s`

default:
    just -l

bootstrap:
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

dump:
    brew bundle dump --formula --cask --tap --mas --force --file {{ brewfile }}

install:
    brew bundle --file {{ brewfile }}
