Plug 'airblade/vim-gitgutter'
Plug 'elzr/vim-json'
Plug 'godlygeek/tabular'
Plug 'hynek/vim-python-pep8-indent'
Plug 'martinda/Jenkinsfile-vim-syntax'
Plug 'plasticboy/vim-markdown'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vividchalk'
Plug 'tsaleh/vim-align'
Plug 'vim-scripts/molokai'

Plug 'tell-k/vim-autopep8'
let g:autopep8_ignore="E501,E221,E251"
