" Tell vim to remember certain things when we exit
"  '10  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files

set nocompatible
set modelines=1
set nu

set tabstop=2
set shiftwidth=2
set expandtab
syntax on
filetype plugin indent on
colorscheme slate
