set nocompatible
set modelines=2
set nu

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set shell=/bin/bash

nmap <F11> :set invpaste<CR>
nmap <F12> :set invnumber<CR>:GitGutterToggle<CR>:SyntasticToggleMode<CR>

" don't create stupid files
set nobackup
set noundofile

" jump to last position when re-opening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif
" except for git commits
autocmd FileType gitcommit call setpos('.', [0, 1, 1, 0])

" fix my damn inability to type
command Qa qa
command Q q
