Bundle 'airblade/vim-gitgutter'
Bundle 'elzr/vim-json'
Bundle 'godlygeek/tabular'
Bundle 'scrooloose/syntastic'
Bundle 'plasticboy/vim-markdown'
Bundle 'tpope/vim-endwise'
Bundle 'tpope/vim-surround'
Bundle 'tsaleh/vim-align'
