Bundle 'airblade/vim-gitgutter'
Bundle 'cometsong/ferm.vim'
Bundle 'godlygeek/tabular'
Bundle 'rodjek/vim-puppet'
Bundle 'scrooloose/syntastic'
Bundle 'tpope/vim-endwise'
Bundle 'tpope/vim-rake'
Bundle 'tsaleh/vim-align'
