#!/usr/bin/env bash

STATE_FILE="$HOME/.dotfiles/.dark-mode.state"

DARK=true
if [ -e "$STATE_FILE" ]; then
  DARK=$(cat "$STATE_FILE")
fi

if [ "$DARK" == "true" ]; then
  cat "$HOME/.config/dunst/theme-dark.conf" "$HOME/.config/dunst/dunstrc" >"$HOME/.config/dunst/final.dunstrc"
else
  cat "$HOME/.config/dunst/theme-light.conf" "$HOME/.config/dunst/dunstrc" >"$HOME/.config/dunst/final.dunstrc"
fi
