# don't tell me about updates
update_check_interval 0
scrollback_lines 100000
copy_on_select yes
cursor_stop_blinking_after 3.0
clipboard_control write-clipboard write-primary no-append

# manage this ourselves
shell_integration disabled

mouse_map left click ungrabbed no_op

enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no

# add some margins
window_padding_width 8

tab_bar_style separator
tab_separator " │ "

font_features JetBrainsMono-Regular +ss19 +zero
map kitty_mod+PLUS change_font_size all +0.5
map kitty_mod+MINUS change_font_size all -0.5
map kitty_mod+0 change_font_size all 0

enabled_layouts tall,grid,stack,vertical
map ctrl+shift+z toggle_layout stack

# unmap ctrl-tabs
map ctrl+tab
map ctrl+shift+tab

# remap to apple style
map ctrl+shift+[ previous_tab
map ctrl+shift+] next_tab
map super+tab next_tab
map super+shift+tab previous_tab
map super+shift+] next_tab
map super+shift+[ previous_tab

map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+n new_os_window_with_cwd

map shift+ctrl+up move_window up
map shift+ctrl+left move_window left
map shift+ctrl+right move_window right
map shift+ctrl+down move_window down

map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+h neighboring_window left
map alt+l neighboring_window right

map --when-focus-on var:IS_NVIM alt+j
map --when-focus-on var:IS_NVIM alt+k
map --when-focus-on var:IS_NVIM alt+h
map --when-focus-on var:IS_NVIM alt+l
map --when-focus-on title:tm alt+j
map --when-focus-on title:tm alt+k
map --when-focus-on title:tm alt+h
map --when-focus-on title:tm alt+l
map --when-focus-on title:Zellij alt+j
map --when-focus-on title:Zellij alt+k
map --when-focus-on title:Zellij alt+h
map --when-focus-on title:Zellij alt+l

map shift+f1 create_marker
map shift+f2 remove_marker
map ctrl+p scroll_to_mark prev
map ctrl+n scroll_to_mark next

map alt+6 disable_ligatures_in all never
map shift+alt+6 disable_ligatures_in all always
