version: "3"

includes:
  terminfo: ./terminfo.yml

tasks:
  all:
    cmds:
      - task: asdf:install
      - task: asdf:update
      - task: pkgs
      - task: emacs:alpine

  pkgs:
    cmds:
      - sudo apk add cabal ghc elixir go nodejs

  asdf:install:
    cmds:
      - "[ -e ~/.asdf ] || git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0"
      - $HOME/.asdf/bin/asdf plugin list | grep -q direnv || $HOME/.asdf/bin/asdf plugin add direnv
      - $HOME/.asdf/bin/asdf global direnv system

  asdf:update:
    cmds:
      - $HOME/.asdf/bin/asdf update
      - "if [ -e ${HOME}/.asdf/plugins ]; then ${HOME}/.asdf/bin/asdf plugin-update --all; fi"

  emacs:alpine:
    deps:
      - terminfo:emacs
    cmds:
      - sudo apk add emacs ncurses ncurses-terminfo procps
      - doom sync
