if-shell -b '[ "$TERM" = "xterm-ghostty" ]' {
  set -g default-terminal "xterm-ghostty"
}
if-shell -b '[ "$TERM" = "xterm-kitty" ]' {
  set -g default-terminal "xterm-kitty"
}

set -a terminal-features '*:RGB' # truecolor
set -g @copy_use_osc52_fallback on

set -g xterm-keys on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

set -g mouse off
set -g status-keys emacs
set -g mode-keys   emacs
set -g clock-mode-style 24
set -g history-limit 12000

set-option -g set-titles on
set-option -g set-titles-string "[#h] tmux"

# Start index of window/pane with 1, because we're humans, not computers
set -g base-index 1
setw -g pane-base-index 1

set-option -g mouse on

unbind-key -n C-Space

# increase the history
set-option -g history-limit 500000

# open splits in cwd
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# don't delay on escape key
set -s escape-time 0

# focus events enabled for terminals that support them
set -g focus-events on

set -g set-clipboard on
set -g word-separators " |{}()[]<>`='\"!@#$%^&*:;,?"

# trigger copy mode by
tui_app="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?(senpai)$'"
bind -n M-Up if-shell "$tui_app" "send-keys M-Up" copy-mode

# launch custom popups
bind -n M-p display-popup -E -w 40% -h 40% "prj"
bind -n M-g display-popup -E -w 80% -h 70% "vcs-tui"

# open a new tab in home
bind-key -n M-t new-window -c ~

# toggle synchronize panes
bind X set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

# Scroll up/down by 1 line, half screen, whole screen
bind -T copy-mode-vi M-Up              send-keys -X scroll-up
bind -T copy-mode-vi M-Down            send-keys -X scroll-down
bind -T copy-mode-vi M-PageUp          send-keys -X halfpage-up
bind -T copy-mode-vi M-PageDown        send-keys -X halfpage-down
bind -T copy-mode-vi PageDown          send-keys -X page-down
bind -T copy-mode-vi PageUp            send-keys -X page-up

# When scrolling with mouse wheel, reduce number of scrolled rows per tick to "2" (default is 5)
bind -T copy-mode-vi WheelUpPane       select-pane \; send-keys -X -N 2 scroll-up
bind -T copy-mode-vi WheelDownPane     select-pane \; send-keys -X -N 2 scroll-down

# smart-splits
set -g @smart-splits_no_wrap '' # to disable wrapping. (any value disables wrapping)

set -g @smart-splits_move_left_key  'M-h'
set -g @smart-splits_move_down_key  'M-j'
set -g @smart-splits_move_up_key    'M-k'
set -g @smart-splits_move_right_key 'M-l'

set -g @smart-splits_resize_left_key  'S-Left'
set -g @smart-splits_resize_down_key  'S-Down'
set -g @smart-splits_resize_up_key    'S-Up'
set -g @smart-splits_resize_right_key 'S-right'

set -g @smart-splits_resize_step_size '3'
set -g @smart-splits_no_wrap 'true'

run-shell ~/.config/tmux/smart-splits.tmux

# zoom toggle
bind -n M-z resize-pane -Z

# tabs (windows)
bind -n C-Tab select-window -n
bind -n C-BTab select-window -p

bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

set -g status on
set -g status-interval 2
set -g status-justify centre
set -g status-position bottom
set -g status-left " #(hostname)"
set -g status-right "%T %F "
set -g window-status-last-style fg=#f0f0f0,bg=#303030

# silence bells
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none

source-file ~/.config/tmux/theme-dark.conf
