alias pki="sudo apt-get install"
alias pkls="dpkg -L"
alias pkp="apt-file search"
alias pks="apt-cache search"
alias pksh="apt-cache show"
alias pku="sudo apt-get update && sudo apt-get --autoremove dist-upgrade"
alias pkr="sudo apt-get remove"
