#alias pki="nix-env -iA "
#alias pkls="dpkg -L"
#alias pkp="apt-file search"
alias pks="nix search "
#alias pksh="apt-cache show"
#alias pku="nix-channel --update && nix-env -u '*'"
#alias pkr="sudo apt-get remove"
