### an-old-hope Theme
## Original Author: sainnhe
# URL: https://github.com/sainnhe/an-old-hope
# License: MIT License

"type" = "blue"
"constant" = "purple"
"constant.numeric" = "purple"
"constant.character.escape" = "orange"
"string" = "yellow"
"comment" = "grey"
"variable" = "fg"
"variable.builtin" = "orange"
"variable.parameter" = "fg"
"variable.other.member" = "fg"
"label" = "orange"
"punctuation" = "grey"
"punctuation.delimiter" = "grey"
"punctuation.bracket" = "fg"
"keyword" = "red"
"operator" = "orange"
"function" = "green"
"function.builtin" = "blue"
"function.macro" = "purple"
"tag" = "yellow"
"namespace" = "blue"
"attribute" = "purple"
"constructor" = "blue"
"module" = "blue"
"special" = "orange"

"markup.heading.marker" = "grey"
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "fg", modifiers = ["bold"] }
"markup.list" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text" = "purple"
"markup.quote" = "grey"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "orange"
"diff.minus" = "red"

"ui.background" = { bg = "bg0" }
"ui.cursor" = { modifiers = ['reversed'] }
"ui.cursor.match" = { fg = "orange", bg = "diff_yellow" }
"ui.cursor.insert" = { fg = "black", bg = "grey" }
"ui.cursor.select" = { fg = "bg0", bg = "blue" }
"ui.selection" = { bg = "bg4" }
"ui.linenr" = "grey"
"ui.linenr.selected" = "fg"
"ui.cursorline.primary" = { bg = "bg2" }
"ui.statusline" = { fg = "fg", bg = "bg3" }
"ui.statusline.insert" = { fg = "black", bg = "blue" }
"ui.statusline.normal" = { fg = "black", bg = "yellow" }
"ui.statusline.insert" = { fg = "black", bg = "green" }
"ui.statusline.inactive" = { fg = "grey", bg = "bg1" }
"ui.popup" = { fg = "grey", bg = "bg2" }
"ui.window" = { fg = "grey", bg = "bg0" }
"ui.help" = { fg = "fg", bg = "bg1" }
"ui.text" = "fg"
"ui.text.focus" = "green"
"ui.menu" = { fg = "fg", bg = "bg2" }
"ui.menu.selected" = { fg = "bg0", bg = "green" }
"ui.virtual.whitespace" = { fg = "grey_dim" }
"ui.virtual.ruler" = { bg = "grey_dim" }

info = { fg = 'green', bg = 'bg2' }
hint = { fg = 'blue', bg = 'bg2', modifiers = ['bold'] }
warning = { fg = 'yellow', bg = 'bg2', modifiers = ['bold'] }
error = { fg = 'red', bg = 'bg2', modifiers = ['bold'] }
diagnostic = { modifiers = ['underlined'] }

[palette]

black = "#181819"
bg0 = "#1c1d21"
bg1 = "#686b78"
bg2 = "#363944"
bg3 = "#3b3e48"
bg4 = "#414550"
bg_red = "#ff6077"
diff_red = "#55393d"
bg_green = "#a7df78"
diff_green = "#394634"
bg_blue = "#85d3f2"
diff_blue = "#354157"
diff_yellow = "#4e432f"
fg = "#cbcdd2"
red = "#eb3d54"
orange = "#f39660"
yellow = "#e5cd52"
green = "#78bd65"
cyan = "#4fb4d8" # added for compatibility with `edge` scheme
blue = "#4fb4d8"
purple = "#ef7c2a"
grey = "#cbcdd2"
grey_dim = "#cbcdd2"
