#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[aliases]
cl-up = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail
INPUT=${1:-"@-"}
HASH=$(jj log -r "${INPUT}" -T commit_id --no-graph)
HASHINFO=$(git log -n 1 ${HASH} --oneline --color=always)
echo "Pushing from commit ${HASHINFO}"
git push gerrit "${HASH}":refs/for/main
""", ""]
home = ["util", "exec", "--", "git-home"]
pr = ["util", "exec", "--", "git-jjpr"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]


[fsmonitor]
backend = "watchman"
watchman.register-snapshot-trigger = true

[git]
sign-on-push = true

[signing]
behavior = "drop"
backend = "ssh"
key = "~/.ssh/signing-key.pub"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

# [template-aliases]
# log_compact = """
#   if(root,
#       format_root_commit(self),
#       label(if(current_working_copy, "working_copy"),
#         concat(
#           separate(" ",
#             format_short_change_id_with_hidden_and_divergent_info(self),
#             if(empty, label("empty", "(empty)")),
#             if(description,
#               description.first_line(),
#               label(if(empty, "empty"), description_placeholder),
#             ),
#             bookmarks,
#             tags,
#             working_copies,
#             if(git_head, label("git_head", "HEAD")),
#             if(conflict, label("conflict", "conflict")),
#             if(config("ui.show-cryptographic-signatures").as_boolean(),
#               format_short_cryptographic_signature(signature)),
#             if(!description && !empty, "\n" ++ diff.summary()),
#           ) ++ "\n",
#         ),
#       )
#     )
# """

# [templates]
# # change id
# commit_trailers = '''
# if(!trailers.contains_key("Change-Id"), format_gerrit_change_id_trailer(self))'''
# # sign off
# commit_trailers = '''
# format_signed_off_by_trailer(self)'''

[ui]
# default-command = ["log", "--template=log_compact"]
diff-editor = ":builtin"
diff-formatter = ":git"
# diff-formatter = ["difft", "--color=always", "$left", "$right"]
editor = "nvim"
pager = ["delta"]
default-command = "status"
# pager = ":builtin"

[user]
name = "Adam C. Stephens"
email = "adam@valkor.net"
