#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[aliases]
cl-up = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail
INPUT=${1:-"@-"}
HASH=$(jj log -r "${INPUT}" -T commit_id --no-graph)
HASHINFO=$(git log -n 1 ${HASH} --oneline --color=always)
echo "Pushing from commit ${HASHINFO}"
git push gerrit "${HASH}":refs/for/main
""", ""]
home = ["util", "exec", "--", "git-home"]
pr = ["util", "exec", "--", "git-jjpr"]
pr-create = ["util", "exec", "--", "jj-pr-create"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

# [fsmonitor]
# backend = "watchman"
# watchman.register-snapshot-trigger = true

[git]
sign-on-push = true

[signing]
behavior = "drop"
backend = "ssh"
key = "~/.ssh/signing-key.pub"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

# [templates]
# # change id
# commit_trailers = '''
# if(!trailers.contains_key("Change-Id"), format_gerrit_change_id_trailer(self))'''
# # sign off
# commit_trailers = '''
# format_signed_off_by_trailer(self)'''

[templates]
draft_commit_description = """
concat(
  builtin_draft_commit_description,
  "\nJJ: ignore-rest\n",
  diff.git(),
)
"""

[ui]
diff-editor = ":builtin"
editor = "nvim"
pager = ["pager"]
default-command = "status"

[user]
name = "Adam C. Stephens"
email = "adam@valkor.net"

# use delta only in diff
[[--scope]]
--when.commands = ["diff"]
[--scope.ui]
pager = ["delta"]
diff-formatter = ":git"
