[aliases]
home = ["util", "exec", "--", "git-home"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

[fsmonitor]
backend = "watchman"
watchman.register-snapshot-trigger = true

[git]
sign-on-push = true

[signing]
behavior = "drop"
backend = "ssh"
key = "~/.ssh/signing-key.pub"

[ui]
default-command = "log"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
diff-editor = ":builtin"
editor = "nvim"
pager = ":builtin"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

[user]
name = "Adam C. Stephens"
email = "adam@valkor.net"

# [templates]
# commit_trailers = '''
# format_signed_off_by_trailer(self)'''
