Metrics/BlockLength:
  Enabled: False
Metrics/LineLength:
  Max: 200
Metrics/MethodLength:
  Enabled: False
Style/StringLiterals:
  Enabled: False
Style/Documentation:
  Enabled: False
Metrics/AbcSize:
  Enabled: False
Style/SymbolArray:
  Enabled: False
Metrics/ClassLength:
  Enabled: False
