-- rule = {
--   matches = {
--     {
--       { "device.nick", "equals", "JDS Labs Atom DAC+" },
--     },
--   },
--   apply_properties = {
--     ["api.alsa.headroom"] = 2048,
--     ["audio.format"] = "S32LE",
--   },
-- }

-- table.insert(alsa_monitor.rules, rule)
