#!/usr/bin/env bash

status() {
  if [ "$STATE" = "Charging" ]; then
    echo -n "charging"

    if [ "$RATE" -gt 0 ]; then
      echo ", $(gettime) left"
    else
      echo ""
    fi
  elif [ "$STATE" = "Discharging" ]; then
    echo "$(gettime)h left"
  else
    echo "fully charged"
  fi
}

color() {
  if [ "$CAPACITY" -le 20 ]; then
    echo "#eb3d54"
  elif [ "$CAPACITY" -le 35 ]; then
    echo "#e5cd52"
  else
    echo "#4fb4d8"
  fi
}

icon() {
  if [ "$CAPACITY" -le 20 ]; then
    echo ""
  elif [ "$CAPACITY" -le 35 ]; then
    echo ""
  elif [ "$CAPACITY" -le 50 ]; then
    echo ""
  elif [ "$CAPACITY" -le 70 ]; then
    echo ""
  else
    echo ""
  fi
}

wattage() {
  echo "$(bc -l <<<"scale=1; $RATE / 1000000") W"
}

gettime() {
  FULL=$(cat /sys/class/power_supply/BAT0/energy_full)
  NOW=$(cat /sys/class/power_supply/BAT0/energy_now)

  if [ "$RATE" -gt 0 ]; then
    if [ "$STATE" = "Discharging" ]; then
      EX="$NOW / $RATE"
    else
      EX="($FULL - $NOW) / $RATE"
    fi
    date -u -d@$(bc -l <<<"$EX * 3600") +%H:%M
  fi
}

while true; do
  RATE=$(cat /sys/class/power_supply/BAT0/power_now)
  CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
  STATE=$(cat /sys/class/power_supply/BAT0/status)

  echo '{ "percentage": "'"$CAPACITY"'", "wattage": "'"$(wattage)"'", "status": "'"$(status)"'", "color": "'"$(color)"'", "icon": "'"$(icon)"'" }'
  sleep 3
done
