---
- hosts: localhost
  connection: local
  tasks:
    - name: homebrews
      homebrew:
        name: "{{ item }}"
        state: present
        update_homebrew: yes
      with_items:
        - colordiff
        - flake8
        - go
        - gnu-sed
        - gnu-tar
        - htop-osx
        - hub
        - jq
        - nmap
        - nodejs
        - npm
        - pstree
        - the_silver_searcher
        - tmate
        - tmux
        - tree
        - wget

    - name: homebrew casks
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - finicky

    - name: vim
      homebrew:
        name: vim
        state: present
        install_options: "--without-python --with-python3"

    - name: upgrade homebrews
      homebrew:
        upgrade_all: yes
