---
- hosts: localhost
  connection: local
  become: False
  tasks:
    - name: gems
      gem:
        name: "{{ item }}"
        state: present
      with_items:
        - bundler
        - rubocop
    - name: tell fresh we're a ruby shop
      file:
        path: "{{ ansible_env['HOME'] }}/.dotfiles/.local/dev-ruby"
        state: touch
