# shellcheck shell=bash

alias cat="bat"
alias cnf="command-not-found"
alias da="direnv allow"
alias db="direnv block"
alias dc="docker-compose"
alias dclf="docker-compose logs --tail=100 -f"
alias dog="doggo"
alias dps='docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}\t{{.Command}}\t{{.Image}}"'

alias f="fossil"
alias fs="fossil status"

alias ga="git add"
alias gbv="git branch --all --verbose --verbose"
alias gc="git commit"
alias gd="git diff"
alias gl="git pull"
alias glo='git log --date=iso --format="%C(auto)%h %C(auto,blue)[%ar]%C(auto)%d %s" --max-count=15'
alias gp="git push"
alias grh="git reset HEAD"
alias grv="git remote -v"
alias gs="git status"
alias gss="git status --short"
alias gsw="git switch"
alias gswc="git switch --create"
alias jjc="jj commit"
alias jjd="jj diff"
alias jjbm="jj bookmark move --to @-"
alias jjgf="jj git fetch --all-remotes"
alias jjgp="jj git push"
alias gw="git worktree"
alias gt="git tag --list -n1"
alias ivl="sudo iptables -vnL --line-numbers"
alias jc="sudo journalctl"
alias jcu="journalctl --user"
alias l="ll -a"
alias ll="eza -lg"
alias nix="nix --print-build-logs"
alias sy="sudo systemctl"
alias syu="systemctl --user"
alias tree="eza --tree"
