version: "3"

tasks:
  bootstrap:
    cmds:
      - fish ~/.dotfiles/bin/theme.fish

  fisher:purge:
    dir: ~/.dotfiles/fish/
    cmds:
      # decors/fish-colored-man
      - rm -f functions/man.fish
      # franciscolourenco/done
      - rm -f conf.d/done.fish
      # h-matsuo/fish-color-scheme-switcher
      - rm -f functions/__scheme* */scheme.fish
      # jorgebucaran/fisher
      - rm -f */fisher.fish
      # oh-my-fish/plugin-foreign-env
      - rm -f functions/fenv.
      # PatrickF1/fzf.fish
      - rm -f conf.d/fzf.fish completions/fzf_configure_bindings.fish functions/_fzf_* functions/fzf_*

  fisher:install:
    deps:
      - fisher:purge
    cmds:
      - ~/.dotfiles/bin/install-fisher.fish
